### ISSUE TITLE
Importer: Improve output when docstrings are formatted unexpectedly

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#159]
##### SUMMARY

After `galaxy-importer` gets docstrings from `ansible-docs` it transforms the tables to allow them to display in the UI. When `contains` are not a dictionary of dictionaries, a traceback is thrown.

```
  File "/galaxy_importer/loaders.py", line 269, in _transform_doc_strings                                                                                                                   
    handle_nested_tables(d, table_key='contains')                                                                     
  File "/galaxy-importer/galaxy_importer/loaders.py", line 255, in handle_nested_tables                                                                                                                     
    obj[table_key] = dict_to_named_list(obj[table_key])                                                               
  File "/galaxy-importer/galaxy_importer/loaders.py", line 249, in dict_to_named_list 
    key in dict_of_dict.keys()                                                                                        
  File "/galaxy-importer/galaxy_importer/loaders.py", line 249, in <listcomp>         
    key in dict_of_dict.keys()                                                                                        
TypeError: 'list' object is not a mapping  
```

This is bug since `contains` can be a `dict`, `list` or `str` with no limit further than that. There is also a bug in the docsite where it does not display `RETURN` docs if this situation occurs. 

##### STEPS TO REPRODUCE
In a `RETURN` docstring under `output:` change a `contains` block from this
```
contains:
  obj_field:
    description:
    - Default set of fields
```
to this
```
contains:
  obj_field:
    - Default set of fields
```

##### EXPECTED RESULTS
Near term: give a warning describing the problem, exclude the unexpected key in docs processing, and allow import to continue.

After the docsite can handle these and decides how to format them, galaxy can follow in the importer and UI.

##### ACTUAL RESULTS
Traceback and import fails

**Comment by abadger** [comment]
is this a bug in the importer or a bug in the documentation?  It looks like a bug in the documentation to me.

**Comment by abadger** [comment]
I ask because I'm working on a converting schema (schema that converts to allowable types instead of failing or passing invalid types through) for the documentation website build and this is one of the things I ran across.  Since there's only a few modules where this happens, my assumption is that it's bad documentation that should be fixed.

**Comment by abadger** [comment]
I hacked up a quick driver for validating against the return_schema inside of validate_modules. https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/sanity/validate-modules/validate_modules/schema.py#L239

```
Traceback (most recent call last):
  File "return-test.py", line 77, in <module>
    v_validate(RETURN_DATA_SUSPECT['return'], schema.return_schema)
  File "/home/badger/.local/lib/python3.8/site-packages/voluptuous/humanize.py", line 40, in validate_with_humanized_errors
    raise Error(humanize_error(data, e, max_sub_error_length))
voluptuous.error.Error: expected a dictionary for dictionary value @ data['obj_type']['contains']['obj_field']. Got ['One or more obj_type fields as specified by return_fields argument or the default set   of fields as per the object type']
```

ansible/ansible currently only has schema for validating modules, not plugins (and the schema are only used when running ansible-test, not when parsing the documentation in ansible-doc).  So this isn't an assurance that the docs are bad.  It's just another data point which might indicate that.

**Comment by awcrosby** [comment]
@abadger in chatting with @sivel the above is valid for `contains`, but maybe we should specify that we expect `contains` to be in a particular format in order to facilitate html display. it feels like this _should_ be a documentation bug.

**Comment by abadger** [comment]
@awcrosby Hmm... Is that because returns has no schema in plugins?  Or is it because it's what we want?  website docs won't display anything for that format so it doesn't seem like it's desirable.

I just wrote a schema wherein that is illegal (it's based on the return schema for modules where, if my test last night was correct, it would have failed as well).  Considering we haven't tested this before, there's surprisingly few things that break with it ;-)  (To be fair, the schema does conversion when it can.  So, for instance, if some wrote `samples:`  instead of `sample:`, the schema will correct it instead of failing.)

I'm going through and submitting fixes for all the `community.*` collections to fix those docs now.

I would like to get something based on this schema into ansible-test at some point.  Probably a stricter version that does not do conversion.  If you use python-3.6+ for your importer, I could give you my schema, as well, and you could use it to both validate and fixup the documentation that you're being given.  (If you want to talk on slack, that might be a better place to have a conversation about this ;-)
