### ISSUE TITLE
Collection POST responds with invalid task URL for status checks

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy_ng#167]
## Bug Report
Affecting QA and CI. When I post a collection, the response that comes back with a task URL to poll for the import status provides the wrong URL. It looks like the URL we may expose for stand-alone mode, not the Insights API routed URLs we need to use here.

POST collection to here:
`https://ci.cloud.redhat.com/api/automation-hub/v3/artifacts/collections/`

Get a task URL here:
`https://ci.cloud.redhat.com/pulp_ansible/galaxy/automation-hub/api/v3/imports/collections/28e37da1-3aff-4a0b-9bca-c48b7c133215/`

**Comment by alikins** [comment]
I think I see the problem (should probably return the get_absolute_url() instead).

it's returning the pulp_ansible task url instead of the collectionImport url
￼
Interesting... galaxy_ng CollectionImport model doesn't have a ref to a Repository or a Distribution to populate the <path> in it's get_absolute_url(). May need to add a field to CollectionImport for that. Which makes sense if CollectionImport is the record of the import which are "to" a particular Repository.
