### ISSUE TITLE
Don't display doc_fragments in the collection plugin documentation on AH

### ISSUE THREAD

**Issue by samccann** [ansible/galaxy_ng#299]
### Use Case

Users want to find out what plugins are available to them to use within playbooks etc from the collections.

Today, the AH plugin list includes doc_fragments and module_utils, neither of which are directly usable to a user of the collection. This extraneous information makes it more difficult for a user  to find what they looking for.

For example,  the amazon.aws collectionhas 7 plugins that can be used in playbooks etc, but AH lists 27.

Today on docs.ansible.com, we do not expose doc_fragments (or module_utils) in the user-facing documentation.  [doc_fragments](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#documentation-fragments) are a developer convenience to add a common 'fragment' of the module docstring across multiple modules.

I noticed this is different on AH:

https://cloud.redhat.com/ansible/automation-hub/amazon/aws/content/doc_fragments/aws

There was some discussion about this on a slack channel, that there is a corner case wherein a customer using the Amazon.aws collection could be writing their own modules and could want to use the doc_fragment in their modules. That seems to me a very small number of potential customers that need this info vs the majority who have to wade through excess doc_fragments (and possibly module_util) entries in AH to find what they are really looking for.  If such information is deemed important, it is more developer documentation, not the user documentation that AH seems best suited to display.

### Alternatives

NOTE: This is based on a brief internal discussion and amazon.aws is only used here as an example, not to imply the collection maintainers agree or disagree with how AH works today, but I didn't want this discussion to get lost on slack so opened this issue for further consideration by AH folks.

**Comment by jborean93** [comment]
I don't feel too strongly either way but one thing to note is that while AH does document the presence of the doc fragment and module_utils it doesn't document the contents of those plugins so a dev/customer who uses them in their own collection would still have to look at the source code to determine what they want to use. This isn't really something AH can fix on the module util side as we have no common documentation interface, technically the doc fragments could be shown but that's also arguably not needed as well.

What I would prefer to see on the docs is a way to see what the plugin type is, right now things are lumped under

* Documentation
* Modules
* Plugins

![image](https://user-images.githubusercontent.com/8462645/87354250-9517e880-c5a1-11ea-80ac-903859cd9ae6.png)

Either we should have sub groups for each plugin type or just split up `Plugins` into their various type groups. That way people who do not care about doc fragments or module utils because they aren't used in playbooks don't have to see them in the AH docs.

**Comment by chouseknecht** [comment]
Migrated to Jira: AAH-53
