### ISSUE TITLE
Infra: Create content repositories

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#39]
Subtask of #20 

- [ ] ~~On system startup for private AH, create 'staging', 'rejected' and 'automation-hub' repositories~~
- [ ] Parameterize repository names so that we're not hardcoding repository names in our business logic.
- [ ] For c.rh.c, create 'staging' and 'rejected' repositories.
- [ ] ~~For c.rh.c, the existing 'automation-hub' repository will become the 'certified' repository.~~
    - ~~This may mean that we use the repository as is, or it could mean that we copy content into a new 'certified' repository.~~
    - ~~If we're not going to copy content to a new repository, we may want to rename the existing repository to 'certified'~~

**Comment by alikins** [comment]
@chouseknecht For:

> On system startup for private AH, create 'unreviewed', 'rejected' and 'certified' repositories

For private AH, for now, there will only be the admin user/org/account/etc, so these will be associated with admin and partner-engineer group.

For c.r.c, what identifier do we want to associate repositories to? I assume group/account. 
- per user?
- per group?
- per RH SSO account/account_number?  

For c.r.c, account_number is only stored as part of the group name, ie rh-identity-account:6269497)
So those are more or less the same. 

At the moment, not sure there is a good way to associate auth credentials on a repo level. Auth tokens are per 'user', so a given auth token would provide auth to all of that users group/accounts repositories. Probably fine for now, and there is still some room for using Permissions that further limit access if needed.

**Comment by chouseknecht** [comment]
@alikins 

For the end-user install we currently create the default repositories with [the config role](httips://galaxy.ansible.com/chouseknecht/ansible_galaxy_config). Maybe there's a better way to do it , not sure; but if not, we can add more repository names [to the list of repos being created](https://github.com/chouseknecht/ansible_galaxy_config/blob/master/tasks/main.yml#L12).

**Comment by alikins** [comment]
I think for the "official" repos for cloud.redhat.com / automation-hub, the names of the repos is more critical than partner or standalone use because:

1. Will be harder to change in the future
1. Kind of sets an example of how folks will name / structure repos for per-account or standalone cases.
1. The ui and the api and data names should be consistent.

For per-partner repos, the names are a little less important because:

1. Inherently of interest to smaller audience
1. There may need to be some flexibility in naming to allow partners to use naming consistent with their release methodology (ie, maybe Cisco wants 'stable', 'beta', 'unofficial' while YoYoDyne may want "StableAndDead", "Stable", "AlmostStableButUnsupported", "QE", "Integration", "SomeJunkWeBoughtAtAStuckeys").
    1. Note: We don't have to actually allow or suggest that level of tweaking, just examples of ways partners workflows and release processes may differ.

**Comment by alikins** [comment]
A note about naming repositories.

In addition to the Repository names, we also need to provide a Distribution 'name' and a Distribution 'base_path'.  They _can_ all be the same by convention. For example, for the 'golden' certified Repository,  Repository.name = Distribtion.name = Distribution.base_path

Since most will be access at /api/automation-hub/content/{distribution_base_path}/v3/collections/...
It will be useful if the Distribution.base_path includes partner identifying info.

And for partners, the repo that is the main production repo should have the shortest most direct name.  (ie, the user facing name for the repo would be "cisco")
Especially if we add some attributes to describe primary / stable / production repos.

For example, for Cisco, the main / stable / certified / prod repo:
Repository.name: 'cisco'
Distribution.name: 'cisco'
Distribution.base_path = 'cisco'
url = '/api/automation-hub/content/cisco/'

And the staging / testing / qe / beta / whatever
Repository.name: 'cisco_staging'
Distribution.name: 'cisco_staging'
Distribution.base_path: 'cisco_staging'
url = '/api/automation-hub/content/cisco_staging/'

I would also suggest sticking with the role/collection naming restrictions for at least Distribution.base_path.  The motivation is that in the future, it may be possible for
ansible / ansible-galaxy to support local fs 'repos' and/or allow the COLLECTION_ROOT
to include an additional top level namespace. Restricting base_path to compatible names
would prevent forcing renaming in the future.

**Comment by chouseknecht** [comment]
@alikins the distribution name and base_path should match the repository name.

Also, there will not be separate staging/certified/stable/prod repositories for partners. We said that a partner will have an inbound repo to which they will publish collections. Their published collection will immediately move to a single, global 'staging' repository, and from there, if certified, will move to the single, global 'automation-hub' repository. The inbound partner repository will be created at the time a namespace is created.

**Comment by chouseknecht** [comment]
Recording the conversation from standup today (24 June):

1. Don't add endpoints without reviewing the @davidn, to make sure that we're delivering what the UI needs and that we're not putting business logic in the UI.
2. At this time, there should not be an endpoint for creating repositories. Repositories will be created on the backend in response to specific events or as a the result of a particular workflow. 
3. On c.rh.c each organization will have a single repository for blacklisting content. This default blacklist and associated repository will be created at authentication time, if does not already exist. This means that each time a user authenticates, the backend will check for the default blacklist and repo, and if it does not exist, create it.

**Comment by alikins** [comment]
https://github.com/ansible/galaxy_ng/pull/315 is WIP of this.

**Comment by davidn** [comment]
> 1. To ensure we're delivering what the UI needs and that we're not putting business logic in the UI, don't add endpoints without first reviewing with @davidn.

Probably meant @newswangerd

**Comment by alikins** [comment]
I think the majority of this is done via #315 and other prs.
