### ISSUE TITLE
[proposal] Roles support?

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy_ng#58]
From the project's README:

> Over time we expect to migrate the web site [galaxy.ansible.com] to this code base, so for now you're looking into the future, and you have an opportunity to help shape that future.

I've glanced through the API in its current state, and it looks like there's only references to storing and distributing collections in this project. The current version of Galaxy supports both roles and collections.

There are currently 23,819 roles on Galaxy, vs 235 collections.

Over time, there will be more collections published, I'm sure. But seeing as there's still [no way to convert roles to collections](https://github.com/ansible/galaxy/issues/2253), what is the plan for supporting roles in this next-gen version of Galaxy?

Or is the plan that roles will be completely unsupported at some point in the future? And if so, when? It would be better to know definitively if roles will or will not be supported so the thousands of current active role maintainers can start making plans for what they'll do with the roles, and when/whether they will convert them to collections (if that becomes a possibility).

Right now it seems like there's an undercurrent of "roles will maybe kinda not be supported someday" but nobody's said anything definitive, and seeing as there's no way for me to convert to collections without breaking all the playbooks in the world using any of my roles, I'm inclined to not work on moving any roles into collections until there are any definitive plans.

**Comment by chouseknecht** [comment]
There are no plans to add support for roles.

**Comment by rhenshall** [comment]
Hi Jeff, as it stands I think having stand alone roles outside of a collection supported in the new code base creates a philosophical problem of why invest in the collections route as we have.  Having said that, and that the world is neither ideal, nor worked out exactly as expected, Roles don't have a satisfactory migration path, so the question is very valid and pertinent.  Rather than adjust the API to support roles, I'd rather we expend effort on making Roles work correctly in the migration journey before we attempt to bridge the divide with a change to the future state of the Galaxy code base.
What we do is introduce a set of time bound dependencies such that before we can institute the migration we have to have solved both Role Migration, and what's happening with existing Roles in the existing Galaxy instance.  If we can't solve those, we need to reassess, but if we don't solve those, we can't proceed.
I think it is correct to set the vision as it is done, however it is not acceptable to have a situation where we don't provide a path.  I think providing that path is the proper investment to promote the future vision and providing an acceptable approach to backwards compatibility.

**Comment by geerlingguy** [comment]
> I think having stand alone roles outside of a collection supported in the new code base creates a philosophical problem of why invest in the collections route as we have. 

I think the main issue is 'maintaining the installation ability for the 24,000 existing roles'—not necessarily supporting further role development.

At a minimum, if we are migrating everything to collections in the long term, so as not to break every installation of Ansible < 2.8 in existence (there are still plenty of users on 2.3, 2.4, 2.5, etc. even though they're not officially supported...), having the ability for users to run `ansible-galaxy install namespace.role` not break would be good—ideally in perpetuity, but if not, via some stopgap measure.

Galaxy is not hosting artifacts for roles, so it seems like it would not be heavy on resource usage, just the time involved in building support for role endpoints into the existing API (read-only, if need be, with no option for role authors to make any changes to anything, and marking every role as deprecated out of the gate).

It is good to push everyone to start using Collections, but right now there is no direct migration path in Galaxy from a role to a collection, and for many use cases (most?) a collection could be as simple as having one role inside, so the impetus for someone like me (none of my roles have any modules/plugins/libraries in them) to move from roles to collections is mostly procedural. If the process is difficult and risks my existing roles' users having issues (either by deleting a role and recreating it as a collection or by role support going away entirely at [x] point in the future), then I'm not going to do it.

**Comment by abeluck** [comment]
This issue was closed on 2020-10-12, but with no accompanying rationale. I've the same concerns as @geerlingguy ::

> Right now it seems like there's an undercurrent of "roles will maybe kinda not be supported someday" but nobody's said anything definitive, and seeing as there's no way for me to convert to collections without breaking all the playbooks in the world using any of my roles, I'm inclined to not work on moving any roles into collections until there are any definitive plans.

Does the closing of this indicate mean standalone roles are being officially deprecated in the future?

**Comment by geerlingguy** [comment]
Posting an update here, about a year in: During today's Ansible Contributor Summit (2021.03 - see [notes](https://hackmd.io/uZDSLOOdS1Kx0xfZVIATmQ)), @nitzmahone presented the following slide:

<img width="564" alt="Screen Shot 2021-03-09 at 11 43 22 AM" src="https://user-images.githubusercontent.com/481677/110522664-bf8d5780-80d6-11eb-87e1-0268a27eff94.png">

So it looks like the idea is there will be some level of standalone role support built into Galaxy NG, so that it can finally replace the current galaxy codebase for https://galaxy.ansible.com
